### ISSUE TITLE
Something's gone wrong [UBUNTU 20.04 LTS]

### ISSUE THREAD

**Issue by codiecher** [mymindstorm/gnome-volume-control#25]
Can adjust volume properly, but I can't access extension settings to hide certain applications that clutter the UI.
![image](https://user-images.githubusercontent.com/49608838/171084818-fbde4046-2a75-4ac0-b2f3-edafd7f4f58a.png)

Sys Info:

OS: Ubuntu 20.04.4 LTS
KERNEL: 5.13.0-41-generic
CPU: Intel Core i7-4790K @ 4.00GHz
GPU: NVIDIA GeForce GTX 1060 3GB
GPU DRIVER: NVIDIA 510.73.05
RAM: 24 GB

**Comment by mymindstorm** [comment]
What version of gjs, gnome, and the extension are you using?

**Comment by codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/171182675-0c59fa7e-35e3-4857-a64b-d7cf8b1fea2c.png)
I'm using v11 of the extension (the latest release)
As for gjs, I'm not very sure how to check that for you.

**Comment by codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/171200441-4409ef19-0d7c-4e50-9c56-508f10960dbd.png)
I would assume this is what you wanted?

**Comment by mymindstorm** [comment]
The v11 version of the extension only supports gnome 42 due to the preferences page using libadwaita.

**Comment by mymindstorm** [comment]
Although the preferences page will not work, if you set the settings manually [according to the schema](https://github.com/mymindstorm/gnome-volume-mixer/blob/master/schemas/net.evermiss.mymindstorm.volume-mixer.gschema.xml) they will probably work.

**Comment by codiecher** [comment]
How exactly actually? This didn't work for me.
![image](https://user-images.githubusercontent.com/49608838/171591199-22c21d57-c770-434d-b522-e5656c18910c.png)
![image](https://user-images.githubusercontent.com/49608838/171591264-49891a7c-dd9c-4309-a1ba-48d32166e788.png)

**Comment by mymindstorm** [comment]
dconf-editor.

**Comment by codiecher** [comment]
Right, thanks. I can confirm that I can hide certain applications with dconf-editor on Gnome 3.36. BTW just wanted to say thanks for maintaining this extension, really essential. Dunno why it doesn't serve along with Ubuntu itself.
